### ISSUE TITLE
error: spawn ./node_modules/.bin/forever enoent

### ISSUE THREAD

**Issue by raimens** [anlambert/webpack-gulp-es6-angular-express#11]
Hey,  this happens when I try to start

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rmend\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webpack-gulp-angular-express-demo@0.0.1~prestart: webpack-gulp-angular-express-demo@0.0.1
6 silly lifecycle webpack-gulp-angular-express-demo@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle webpack-gulp-angular-express-demo@0.0.1~start: webpack-gulp-angular-express-demo@0.0.1
8 verbose lifecycle webpack-gulp-angular-express-demo@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle webpack-gulp-angular-express-demo@0.0.1~start: PATH: C:\Users\rmend\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\rmend\Documents\development\filix2\node_modules\.bin;C:\Program Files (x86)\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Skype\Phone\;C:\Users\rmend\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Users\rmend\AppData\Roaming\npm
10 verbose lifecycle webpack-gulp-angular-express-demo@0.0.1~start: CWD: C:\Users\rmend\Documents\development\filix2
11 silly lifecycle webpack-gulp-angular-express-demo@0.0.1~start: Args: [ '/d /s /c', 'gulp run --NODE_ENV=production' ]
12 silly lifecycle webpack-gulp-angular-express-demo@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle webpack-gulp-angular-express-demo@0.0.1~start: Failed to exec start script
14 verbose stack Error: webpack-gulp-angular-express-demo@0.0.1 start: `gulp run --NODE_ENV=production`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\rmend\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\rmend\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid webpack-gulp-angular-express-demo@0.0.1
16 verbose cwd C:\Users\rmend\Documents\development\filix2
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\rmend\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.4.7
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error webpack-gulp-angular-express-demo@0.0.1 start: `gulp run --NODE_ENV=production`
22 error Exit status 1
23 error Failed at the webpack-gulp-angular-express-demo@0.0.1 start script 'gulp run --NODE_ENV=production'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack-gulp-angular-express-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp run --NODE_ENV=production
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack-gulp-angular-express-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack-gulp-angular-express-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by anlambert** [comment]
Thanks for reporting the issue, it is now fixed in the master branch
