### ISSUE TITLE
How to register a service ....

### ISSUE THREAD

**Issue by liu-kanghui** [anlambert/webpack-gulp-es6-angular-express#2]
Hey Antoine
Can you write an example how to write a service, then register it and use it.  
in the index.js  i see there is registerAngularModule   for directive  but how should I do it  with service? 

I really appreciate your help !!!!

Thanks in advance!

**Comment by anlambert** [comment]
Hey Kangui,

I have just committed an example on how to register an angular service.
Nevertheless, you can see 'registerAngularModule' as an alias for 'angular.module'
so you can use it to register all types of angular components. Its purpose is only to add support for es6 classes for directive and factory.
