### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by liu-kanghui** [anlambert/webpack-gulp-es6-angular-express#4]
Hey Antoine!

Thank you so much for your awesome work!
I was trying to download the new repo  after I did npm install   and  npm start

it throws me error  can't find module npm 

module.js:341
    throw err;
    ^

Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
 at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by anlambert** [comment]
Hum, that's weird ...

Maybe you can try to upgrade npm globally by entering the following command in a shell:
$ npm install -g npm

You may need to run that command as an administrator (sudo ...)

On my side, I used Ubuntu as my operating system coupled to node 6.X and everything works just fine.

You can also try to remove the 'node_modules' folder of the project and do 'npm install' again

**Comment by liu-kanghui** [comment]
I just update my npm and node to 6X.   and i did sudo npm install -g npm   i am using MAX OX. 

Here is the log. 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.9.2
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webpack-gulp-angular-express-demo@0.0.1~prestart: webpack-gulp-angular-express-demo@0.0.1
6 silly lifecycle webpack-gulp-angular-express-demo@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle webpack-gulp-angular-express-demo@0.0.1~start: webpack-gulp-angular-express-demo@0.0.1
8 verbose lifecycle webpack-gulp-angular-express-demo@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle webpack-gulp-angular-express-demo@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kanghuiliu/Downloads/node6.2express/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle webpack-gulp-angular-express-demo@0.0.1~start: CWD: /Users/kanghuiliu/Downloads/node6.2express
11 silly lifecycle webpack-gulp-angular-express-demo@0.0.1~start: Args: [ '-c', 'gulp run --NODE_ENV=production' ]
12 silly lifecycle webpack-gulp-angular-express-demo@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle webpack-gulp-angular-express-demo@0.0.1~start: Failed to exec start script
14 verbose stack Error: webpack-gulp-angular-express-demo@0.0.1 start: `gulp run --NODE_ENV=production`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid webpack-gulp-angular-express-demo@0.0.1
16 verbose cwd /Users/kanghuiliu/Downloads/node6.2express
17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.0
20 error npm  v3.9.2
21 error code ELIFECYCLE
22 error webpack-gulp-angular-express-demo@0.0.1 start: `gulp run --NODE_ENV=production`
22 error Exit status 1
23 error Failed at the webpack-gulp-angular-express-demo@0.0.1 start script 'gulp run --NODE_ENV=production'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack-gulp-angular-express-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp run --NODE_ENV=production
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack-gulp-angular-express-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack-gulp-angular-express-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by anlambert** [comment]
Okay, it must be a MacOS related issue. I did not check the support of my project on that system. 
Hopefully for you, I have got some MacOS VMs on VirtualBox. I will look at it tonight, I keep you posted.

**Comment by anlambert** [comment]
Okay, problem solved. I found a more portable way to get the npm version from a node script.
git pull, npm install, npm run test-frontend and it should now work on MacOS.

**Comment by liu-kanghui** [comment]
Yes yes it works now !   you are so fast and so good at this!!!!  I really wish I could be as good as you are with web development.     already "fell in love with you" hahahaha    

Thank you very much! 💯
