### ISSUE TITLE
Node_modules inside src folder

### ISSUE THREAD

**Issue by liu-kanghui** [anlambert/webpack-gulp-es6-angular-express#7]
Hello Antoine!

Can you delete the bootstrap webpack inside the src folder and put it in the package json?

**Comment by anlambert** [comment]
Actually I can't as I had to patch the bootstrap-webpack module in order for my project to compile. Been a while since I did this, so let me a couple of days to remember why (week-end for me, sorry) in order to fix correctly that hack (maybe a PR, surely a fork, wait and see ...)

**Comment by anlambert** [comment]
Hey Kanghui,

I managed to use the upstream version of bootstrap-webpack. I had to patch the module because there was errors with the jshint webpack preloader when importing the bootstrap config scripts. I simply exclude those files from the jshint preloader in order to fix that issue. 

Cheers
